import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
// @ts-ignore build/server is generated by remix vite:build.
import * as build from "../build/server";
import { getLoadContext } from "../load-context";

export const onRequest = createPagesFunctionHandler({
  build: build as any,
  getLoadContext,
});
